env: "local" # dev, prod
grpc:
  port: 44044
  timeout: 5s
db:
  username: "postgres"
  host: "localhost"
  port: 5432
  dbname: "book_service_db"
  sslmode: "disable"
  password: "qwerty"
redis_db:
  addr: "redis:6379"
  password: "qwerty"
  db: 0
  ttl: 60
  username: "redis"